import { LocationData } from '@/types/location';

// ── Kids-type activities ────────────────────────────────────────────
const kidsActivities = [
    { name: 'Trampoline Zone', emoji: '🤸', description: 'Bounce, flip and soar on our interconnected trampolines designed for young jumpers.', ageGroup: '3–14 yrs', color: '#f67edd' },
    { name: 'Soft Play Area', emoji: '🧸', description: 'A safe, padded wonderland for toddlers and little ones to crawl, climb and explore.', ageGroup: '1–6 yrs', color: '#00b9e3' },
    { name: 'Ball Pool', emoji: '🟡', description: 'Dive into thousands of colourful balls in our giant ball pit — pure joy for kids!', ageGroup: '2–10 yrs', color: '#ffc60b' },
    { name: 'Slide Zone', emoji: '🛝', description: 'Multi-lane racing slides and spiral slides for endless sliding fun.', ageGroup: '3–12 yrs', color: '#6dc065' },
    { name: 'Obstacle Course', emoji: '🏅', description: 'Navigate through tunnels, balance beams and climbing nets in our ninja course.', ageGroup: '5–14 yrs', color: '#ff5da0' },
    { name: 'Rock Climbing', emoji: '🧗', description: 'Scaled-down climbing walls with colourful grips perfect for little adventurers.', ageGroup: '5–14 yrs', color: '#8869d2' },
];

// ── Adults+Kids-type activities ─────────────────────────────────────
const adultsKidsActivities = [
    { name: 'Trampoline Zone', emoji: '🤸', description: 'High-performance trampolines for all ages — freestyle, dodgeball and slam-dunk!', ageGroup: 'All ages', color: '#ff661a' },
    { name: 'Ninja Warrior Course', emoji: '🥷', description: 'Test your strength and agility on our full-size ninja obstacle course.', ageGroup: '8+ yrs', color: '#ff3645' },
    { name: 'Rock Climbing Wall', emoji: '🧗', description: 'Multi-difficulty climbing walls from beginner to expert — harness included.', ageGroup: '6+ yrs', color: '#4facfe' },
    { name: 'Foam Pit', emoji: '🟦', description: 'Launch off the trampoline and land in our massive foam cube pit.', ageGroup: 'All ages', color: '#00b9e3' },
    { name: 'Soft Play Area', emoji: '🧸', description: 'A safe, cushioned play zone specially designed for toddlers and small children.', ageGroup: '1–6 yrs', color: '#ffc60b' },
    { name: 'Dodgeball Arena', emoji: '🏐', description: 'Bouncy dodgeball on trampolines — the ultimate team challenge!', ageGroup: '8+ yrs', color: '#b2d235' },
    { name: 'Basketball Dunk', emoji: '🏀', description: 'Bounce sky-high and slam-dunk like a pro on our trampoline basketball courts.', ageGroup: '6+ yrs', color: '#8869d2' },
];

// ── Hyderabad-specific activities ──────────────────────────────────
const hyderabadActivities = [
    { name: 'Infinity Trampoline', emoji: '🤸', description: 'Jump endlessly across interconnected trampolines built for energetic fun and gravity-defying jumps.', ageGroup: 'All ages', color: '#ff661a' },
    { name: 'Dodge Ball', emoji: '🏐', description: 'Duck, dodge and throw your way to victory in an action-packed trampoline dodgeball showdown.', ageGroup: '8+ yrs', color: '#ff3645' },
    { name: 'Sky Stepper', emoji: '🪜', description: 'Test your balance and confidence as you step across elevated platforms high above the ground.', ageGroup: '8+ yrs', color: '#4facfe' },
    { name: 'Adventure', emoji: '🧗', description: 'Climb, crawl and conquer exciting obstacles designed to challenge agility, strength and coordination.', ageGroup: '6+ yrs', color: '#00b9e3' },
    { name: 'Wall Climbing', emoji: '🧱', description: 'Scale colourful climbing walls with varying difficulty levels for an exciting vertical adventure.', ageGroup: '6+ yrs', color: '#6dc065' },
    { name: 'Donut Slide', emoji: '🍩', description: 'Hop onto an inflatable tube and enjoy a fast, thrilling ride down our exciting donut slide.', ageGroup: 'All ages', color: '#b2d235' },
    { name: 'Tunnel Slide', emoji: '🛝', description: 'Twist and zoom through enclosed tunnels for a smooth, speedy and laughter-filled sliding adventure.', ageGroup: 'All ages', color: '#8869d2' },
    { name: 'Zorb Ball', emoji: '🔮', description: 'Step inside a giant inflatable sphere and roll, bounce, and tumble for an unforgettable thrill.', ageGroup: '8+ yrs', color: '#ff5da0' },
    { name: 'Zip Line', emoji: '🚡', description: 'Step off the platform and soar through the air on an exhilarating zip line ride filled with high-flying fun.', ageGroup: '8+ yrs', color: '#f67edd' },
    { name: 'Bar Dodger', emoji: '🚧', description: 'Duck, jump, and weave past fast-spinning padded beams in a thrilling, high-energy test of speed and agility.', ageGroup: '8+ yrs', color: '#ffc60b' },
    { name: '360 Cycle', emoji: '🚲', description: 'Pedal your way into a complete 360° loop for an adrenaline-filled cycling experience like no other.', ageGroup: '12+ yrs', color: '#00d9a6' },
    { name: 'Battle Beam', emoji: '⚔️', description: 'Grab a padded pugil stick, keep your balance, and knock your opponent off the beam into the soft foam pit below!', ageGroup: '8+ yrs', color: '#ff3645' },
];

// ── DSL Virtue Mall specific activities ─────────────────────────────
const dslVirtueActivities = [
    { name: 'Wave Slide', emoji: '🛝', description: 'Glide down our thrilling Wave Slide and feel the rush of fun as you swoosh through smooth waves of excitement!', ageGroup: 'All ages', color: '#ff661a' },
    { name: 'Sand Pit', emoji: '🏖️', description: 'Build castles, dig tunnels, or just enjoy the soft touch of sand in this creative and calming play zone.', ageGroup: '1–8 yrs', color: '#ff3645' },
    { name: 'Soft Play Area', emoji: '🧸', description: 'A safe, cushioned wonderland where kids can jump, climb, and tumble freely without a worry in the world.', ageGroup: '1–6 yrs', color: '#4facfe' },
    { name: 'Cow Game', emoji: '🐄', description: 'Step into the barnyard for some moo-velous fun—try your hand at our interactive cow game and see if you have the ultimate farmer\'s touch!', ageGroup: '3–10 yrs', color: '#00b9e3' },
    { name: 'Toshi Net', emoji: '🕸️', description: 'Enter a magical, giant cocoon of colorful yarn, built entirely for leaping, laughing, and make-believe play!', ageGroup: '4–12 yrs', color: '#6dc065' },
    { name: 'Tunnel Slide', emoji: '🌀', description: 'Zoom through twisty tunnels that spark excitement and make every slide a surprise-filled adventure.', ageGroup: 'All ages', color: '#b2d235' },
    { name: 'Merry Go Round', emoji: '🎠', description: 'Spin, laugh, and twirl to your heart’s delight — the classic ride that never goes out of style!', ageGroup: '2–8 yrs', color: '#8869d2' },
    { name: 'Zebra Swing', emoji: '🦓', description: 'Hop on the zebra and swing away — balancing fun and thrill in one adorable ride.', ageGroup: '2–8 yrs', color: '#ff5da0' },
    { name: 'Foam Pit', emoji: '🟦', description: 'Leap high and land soft in our fluffy foam cubes — a safe spot for flips, jumps, and fearless fun!', ageGroup: 'All ages', color: '#f67edd' },
    { name: 'Horn Slide', emoji: '📯', description: 'Slide down the playful Horn Slide and enjoy a smooth, curvy ride that ends with giggles and excitement!', ageGroup: 'All ages', color: '#ffc60b' },
    { name: 'Ball Pool', emoji: '🟡', description: 'Dive into a sea of colorful balls — perfect for giggles, splashes of joy, and endless playtime memories.', ageGroup: '2–10 yrs', color: '#00d9a6' },
    { name: 'Interactive Ball Pool', emoji: '🎮', description: 'Experience play like never before with lights, sounds, and motion games in our high-tech interactive ball pool!', ageGroup: '3–12 yrs', color: '#ff3645' },
    { name: 'Wall Climb', emoji: '🧗', description: 'Challenge yourself on our epic Climbing Wall — push your limits, find your footing, and race to the summit for endless vertical fun', ageGroup: '5+ yrs', color: '#4facfe' },
    { name: 'Donut Slide', emoji: '🍩', description: 'Spin, slide, and laugh your way down the Donut Slide — a twisting tunnel of pure joy that guarantees a rush of fun every time!', ageGroup: 'All ages', color: '#6dc065' },
];

// ── Shared opening hours ────────────────────────────────────────────
const WEEKDAY_HOURS = '11:00 AM – 9:30 PM';
const WEEKEND_HOURS = '11:00 AM – 10:00 PM';

// ── Helper: standard safety FAQs appended to every location ─────────
function makeFaqs(citySpecific: { question: string; answer: string }[]) {
    return [
        ...citySpecific,
        { question: 'Is it safe for toddlers?', answer: 'Absolutely! We have dedicated soft play zones with padded surfaces designed specifically for children aged 1–5 years.' },
        { question: 'Do adults need to buy a ticket?', answer: 'Accompanying adults who are not playing can enter for free. Adults who wish to play need a valid ticket.' },
        { question: 'What should we wear?', answer: 'Comfortable clothes and grip socks are recommended. We provide grip socks at the venue if you don\'t have your own.' },
        { question: 'Can I host a birthday party here?', answer: 'Yes! We offer multiple birthday party packages with dedicated hosts, decorations, and food options. Contact us for details.' },
        { question: 'Is photography allowed?', answer: 'Personal photography is welcome. For professional shoots or commercial use, please contact our management in advance.' },
    ];
}

// ── All 21 locations ────────────────────────────────────────────────
export const locations: LocationData[] = [

    // ─── 1. Kolkata ABC Square (adults-kids) ──────────────────────────
    {
        slug: 'kolkata-abc-square-building-best-adult-trampoline-park',
        type: 'adults-kids',
        city: 'Kolkata',
        mall: 'ABC Square Building',
        stateName: 'West Bengal',
        heroImages: ['/image/locations/kolkata-abc/hero-1.jpg', '/image/locations/kolkata-abc/hero-2.jpg', '/image/locations/kolkata-abc/hero-3.jpg'],
        h1: 'Kolkata\'s Ultimate Trampoline & Adventure Park',
        subtitle: 'Bounce, flip, climb & conquer at ABC Square — Kolkata\'s biggest indoor action zone for adults & kids alike.',
        introHeading: 'Ultimate Fun Awaits',
        introText: 'Welcome to Jus Jumpin, ABC Square Building, the ultimate destination for fun and fitness. Jump into an exciting world of laughter and joy, where age is truly just a number! Jus Jumpin at the ABC Square building is meticulously designed with two dedicated play zones; one to host toddlers and kids to enjoy, and another exciting trampoline park for kids in an adult\'s body. Both areas consist of wholesome play zones, thrilling physical activities, a dynamic trampoline park, and interactive indoor games. Our dedicated team ensures endless fun with paramount safety standards and well-maintained hygiene.',
        flipCardImage: '/image/locations/kolkata-abc/hero-1.jpg',
        flipCardBullets: ['7+ activity zones for all ages', 'Full-size ninja warrior course', 'Dedicated toddler soft play', 'Party rooms & event hosting'],
        highlights: [
            { title: 'Adrenaline Rush', emoji: '⚡', paragraph: 'Alongside our energetic and action-filled amusement park, Jus Jumpin, also offers a dedicated party area that is just perfect for hosting unforgettable birthday parties for kids and adults, corporate events, and more.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)', image: '/image/locations/kolkata-abc/hero-1.jpg' },
            { title: 'Family Friendly', emoji: '👨‍👩‍👧‍👦', paragraph: 'Customized theme decorations, flexible packages tailored to your needs, and a dedicated team to ensure your party remains stress-free, hassle-free, and free from all boring stuff.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)', image: '/image/locations/kolkata-abc/hero-1.jpg' },
            { title: 'Premium Safety', emoji: '🛡️', paragraph: 'Every zone features international-grade padding, trained supervisors and strict hygiene protocols.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)', image: '/image/locations/kolkata-abc/hero-1.jpg' },
            { title: 'Celebrate Here', emoji: '🎉', paragraph: 'At Jus Jumpin, We strive to go beyond ordinary. Our thoughtfully designed, vibrant space radiates energy, generates laughter, and creates memories that last for years.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)', image: '/image/locations/kolkata-abc/hero-1.jpg' },
        ],
        activities: adultsKidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹499', weekend: '₹599' },
            { label: 'Child (2 hr)', weekday: '₹799', weekend: '₹899' },
            { label: 'Adult (1 hr)', weekday: '₹599', weekend: '₹699' },
            { label: 'Adult (2 hr)', weekday: '₹899', weekend: '₹999' },
            { label: 'Combo (Adult+Child)', weekday: '₹999', weekend: '₹1199' },
        ],
        ticketNote: 'Grip socks included. Infants under 1 year enter free.',
        address: 'ABC Square Building, 3rd Floor, 28 Camac Street, Kolkata, West Bengal 700016',
        phone: '+91 90000 00001',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3684.5!2d88.35!3d22.54!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjLCsDMyJzI0LjAiTiA4OMKwMjEnMDAuMCJF!5e0!3m2!1sen!2sin!4v1',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+ABC+Square+Kolkata',
        reviewUrl: 'https://g.page/r/jusjumpin-kolkata-abc/review',
        lat: 22.5400,
        lng: 88.3500,
        faqs: makeFaqs([
            { question: 'Where exactly is Jus Jumpin in ABC Square?', answer: 'We are located on the 3rd floor of ABC Square Building, 28 Camac Street, Kolkata. Take the elevator or escalator to the 3rd floor.' },
            { question: 'Is there parking available?', answer: 'Yes, ABC Square has basement and multilevel parking available for visitors.' },
        ]),
        seoTitle: 'Jus Jumpin Kolkata ABC Square — Best Trampoline Park for Adults & Kids',
        seoDescription: 'Visit Jus Jumpin at ABC Square, Kolkata — the ultimate indoor trampoline & adventure park for adults and kids. Ninja course, foam pit, trampolines & more!',
        seoKeywords: 'trampoline park kolkata, jus jumpin abc square, indoor play area kolkata, adventure park kolkata adults',
        accentColor: '#ff661a',
    },

    // ─── 2. Bengaluru M5 Ecity Mall (kids) ───────────────────────────
    {
        slug: 'bengaluru-m5-ecity-mall',
        type: 'kids',
        city: 'Bengaluru',
        mall: 'M5 Ecity Mall',
        stateName: 'Karnataka',
        heroImages: ['/images/locations/bengaluru-m5/hero-1.jpg', '/images/locations/bengaluru-m5/hero-2.jpg', '/images/locations/bengaluru-m5/hero-3.jpg'],
        h1: 'Bengaluru\'s Favourite Kids Play Park',
        subtitle: 'A magical indoor playground where little ones bounce, slide and explore at M5 Ecity Mall.',
        introHeading: 'Welcome to Jus Jumpin — M5 Ecity Mall, Bengaluru',
        introText: 'Nestled inside M5 Ecity Mall in Electronic City, Jus Jumpin is Bengaluru\'s go-to destination for kids\' active play. Our colourful zones are designed to spark imagination and keep children moving.',
        flipCardImage: '/images/locations/bengaluru-m5/flip.jpg',
        flipCardBullets: ['6 vibrant activity zones', 'Dedicated toddler area', 'Trained play supervisors', 'Birthday party packages'],
        highlights: [
            { title: 'Boundless Fun', emoji: '🌈', paragraph: 'From trampolines to ball pools, every corner is designed to bring smiles and laughter to your little ones.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
            { title: 'Safe & Clean', emoji: '✨', paragraph: 'Sanitised zones, padded surfaces and trained staff ensure a worry-free experience for parents.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Learn Through Play', emoji: '🧠', paragraph: 'Our obstacle courses and climbing walls develop motor skills, balance and confidence in children.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Party Central', emoji: '🎂', paragraph: 'Host your child\'s dream birthday with themed decorations, a dedicated host and endless fun.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'M5 Ecity Mall, 2nd Floor, Neeladri Road, Electronic City Phase 1, Bengaluru, Karnataka 560100',
        phone: '+91 90000 00002',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.2!2d77.66!3d12.84!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTLCsDUwJzI0LjAiTiA3N8KwMzknMzYuMCJF!5e0!3m2!1sen!2sin!4v1',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+M5+Ecity+Mall+Bengaluru',
        reviewUrl: 'https://g.page/r/jusjumpin-bengaluru-m5/review',
        lat: 12.8400,
        lng: 77.6600,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in M5 Ecity Mall?', answer: 'We\'re on the 2nd floor of M5 Ecity Mall, Neeladri Road, Electronic City Phase 1.' },
            { question: 'Is it suitable for toddlers under 3?', answer: 'Yes! We have a dedicated soft play area with extra-padded surfaces designed for children aged 1–3.' },
        ]),
        seoTitle: 'Jus Jumpin Bengaluru M5 Ecity Mall — Best Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at M5 Ecity Mall, Bengaluru — the best indoor kids play area with trampolines, ball pools, slides & more. Fun for ages 1–14!',
        seoKeywords: 'kids play area bengaluru, trampoline park electronic city, jus jumpin bengaluru, indoor playground bengaluru',
        accentColor: '#f67edd',
    },

    // ─── 3. Kolkata Avani Mall (kids) ─────────────────────────────────
    {
        slug: 'kolkata-avani-mall',
        type: 'kids',
        city: 'Kolkata',
        mall: 'Avani Mall',
        stateName: 'West Bengal',
        heroImages: ['/images/locations/kolkata-avani/hero-1.jpg', '/images/locations/kolkata-avani/hero-2.jpg', '/images/locations/kolkata-avani/hero-3.jpg'],
        h1: 'Jump Into Joy at Avani Mall, Kolkata',
        subtitle: 'Kolkata\'s colourful indoor kids play zone with trampolines, slides and endless adventure.',
        introHeading: 'Welcome to Jus Jumpin — Avani Mall, Kolkata',
        introText: 'Avani Mall\'s Jus Jumpin is where Kolkata families come for the best kids\' active entertainment. Bright, safe and packed with fun zones, it\'s the perfect escape for little adventurers.',
        flipCardImage: '/images/locations/kolkata-avani/flip.jpg',
        flipCardBullets: ['Vibrant trampoline zone', 'Giant ball pool', 'Safe for toddlers', 'Weekend party bookings'],
        highlights: [
            { title: 'Jump & Play', emoji: '🤸', paragraph: 'Interconnected trampolines and bouncy zones that keep kids active, happy and coming back for more.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Toddler Haven', emoji: '👶', paragraph: 'A gated, extra-padded area just for the littlest ones — so parents can relax while tots explore.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
            { title: 'Clean & Hygienic', emoji: '🧼', paragraph: 'Regular sanitisation after every session and trained staff keeping a watchful eye at all times.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Birthday Bash', emoji: '🎈', paragraph: 'Private party rooms with themed decorations, cake arrangements and a dedicated birthday host.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'Avani Mall, 2nd Floor, Jessore Road, Kolkata, West Bengal 700124',
        phone: '+91 90000 00003',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3683.5!2d88.40!3d22.59!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Avani+Mall+Kolkata',
        reviewUrl: 'https://g.page/r/jusjumpin-kolkata-avani/review',
        lat: 22.5900,
        lng: 88.4000,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Avani Mall?', answer: 'We are on the 2nd floor of Avani Mall, Jessore Road, Kolkata.' },
            { question: 'Is there a separate area for younger kids?', answer: 'Yes, we have a dedicated soft play zone for children aged 1–4 with extra safety padding.' },
        ]),
        seoTitle: 'Jus Jumpin Kolkata Avani Mall — Indoor Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at Avani Mall, Kolkata — fun-filled indoor trampoline park and play area for kids with ball pools, slides, climbing walls & more.',
        seoKeywords: 'kids play area kolkata, trampoline park avani mall, indoor playground kolkata, jus jumpin avani',
        accentColor: '#00b9e3',
    },

    // ─── 4. Kolkata Axis Mall (kids) ──────────────────────────────────
    {
        slug: 'kolkata-axis-mall',
        type: 'kids',
        city: 'Kolkata',
        mall: 'Axis Mall',
        stateName: 'West Bengal',
        heroImages: ['/images/locations/kolkata-axis/hero-1.jpg', '/images/locations/kolkata-axis/hero-2.jpg', '/images/locations/kolkata-axis/hero-3.jpg'],
        h1: 'Bounce & Play at Axis Mall, Kolkata',
        subtitle: 'Premium indoor play park for kids — trampolines, slides and adventure at New Town\'s favourite mall.',
        introHeading: 'Welcome to Jus Jumpin — Axis Mall, Kolkata',
        introText: 'Located in the heart of New Town at Axis Mall, our play park offers Kolkata families a world-class indoor entertainment experience with zones designed for every age group.',
        flipCardImage: '/images/locations/kolkata-axis/flip.jpg',
        flipCardBullets: ['Premium trampoline zone', 'Multi-slide complex', 'Supervised play areas', 'Birthday party venue'],
        highlights: [
            { title: 'Active Play', emoji: '🏃', paragraph: 'From obstacle courses to climbing walls, every zone encourages movement, fitness and fun.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Kid Safe', emoji: '🔒', paragraph: 'Entry/exit controlled zones, CCTV coverage and trained supervisors throughout the facility.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Slide Paradise', emoji: '🛝', paragraph: 'Racing slides, spiral slides and drop slides — the slide zone alone is worth the visit!', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Celebrations', emoji: '🥳', paragraph: 'Book a birthday party with private rooms, themed setups and unlimited playtime for guests.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'Axis Mall, 3rd Floor, New Town, Rajarhat, Kolkata, West Bengal 700156',
        phone: '+91 90000 00004',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3683.0!2d88.45!3d22.58!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Axis+Mall+Kolkata',
        reviewUrl: 'https://g.page/r/jusjumpin-kolkata-axis/review',
        lat: 22.5800,
        lng: 88.4500,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Axis Mall?', answer: 'We are on the 3rd floor of Axis Mall, New Town, Rajarhat.' },
            { question: 'Can I bring outside food?', answer: 'Outside food is not permitted inside the play area, but the mall has a food court with plenty of options.' },
        ]),
        seoTitle: 'Jus Jumpin Kolkata Axis Mall — Kids Trampoline Park & Indoor Play Area',
        seoDescription: 'Visit Jus Jumpin at Axis Mall, New Town, Kolkata — premium indoor trampoline park and play area for kids with slides, obstacle courses & more.',
        seoKeywords: 'trampoline park new town kolkata, kids play area axis mall, indoor playground kolkata, jus jumpin axis mall',
        accentColor: '#6dc065',
    },

    // ─── 5. Kolkata City Centre 2 (kids) ──────────────────────────────
    {
        slug: 'kolkata-city-centre-2',
        type: 'kids',
        city: 'Kolkata',
        mall: 'City Centre 2',
        stateName: 'West Bengal',
        heroImages: ['/images/locations/kolkata-cc2/hero-1.jpg', '/images/locations/kolkata-cc2/hero-2.jpg', '/images/locations/kolkata-cc2/hero-3.jpg'],
        h1: 'Fun Unlimited at City Centre 2, Kolkata',
        subtitle: 'New Town\'s most loved kids play park — bounce, slide and explore in a safe, vibrant space.',
        introHeading: 'Welcome to Jus Jumpin — City Centre 2, Kolkata',
        introText: 'Jus Jumpin at City Centre 2 brings the magic of active play to New Town. Designed for kids of all ages, our vibrant zones spark joy, creativity and healthy movement.',
        flipCardImage: '/images/locations/kolkata-cc2/flip.jpg',
        flipCardBullets: ['Interconnected trampolines', 'Soft play for toddlers', 'Adventure obstacle course', 'Group & party bookings'],
        highlights: [
            { title: 'Bounce Zone', emoji: '🔵', paragraph: 'Our flagship trampoline area lets kids bounce freely with interconnected beds and padded walls.', gradient: 'linear-gradient(135deg, #4facfe, #00b9e3)' },
            { title: 'Tiny Tots', emoji: '🍼', paragraph: 'A separate, gated zone exclusively for children under 5 with soft foam structures and gentle slides.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
            { title: 'Adventure Trail', emoji: '🗺️', paragraph: 'Navigate rope bridges, crawl tunnels and balance beams on our exciting obstacle trail.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Memorable Parties', emoji: '🎊', paragraph: 'Celebrate milestones with our all-inclusive party packages including play, food and decorations.', gradient: 'linear-gradient(135deg, #8869d2, #f67edd)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'City Centre 2, 3rd Floor, New Town, Rajarhat, Kolkata, West Bengal 700157',
        phone: '+91 90000 00005',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3682.8!2d88.47!3d22.59!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+City+Centre+2+Kolkata',
        reviewUrl: 'https://g.page/r/jusjumpin-kolkata-cc2/review',
        lat: 22.5900,
        lng: 88.4700,
        faqs: makeFaqs([
            { question: 'Which floor is Jus Jumpin on at City Centre 2?', answer: 'We are on the 3rd floor of City Centre 2, New Town, Rajarhat.' },
            { question: 'How long can my child play?', answer: 'Standard sessions are 1 or 2 hours. You can extend at the counter subject to availability.' },
        ]),
        seoTitle: 'Jus Jumpin Kolkata City Centre 2 — Kids Trampoline Park & Play Area',
        seoDescription: 'Jus Jumpin at City Centre 2, New Town, Kolkata — indoor trampoline park for kids with trampolines, ball pools, slides and soft play zones.',
        seoKeywords: 'kids trampoline park city centre 2, play area new town kolkata, jus jumpin city centre, indoor play kolkata',
        accentColor: '#4facfe',
    },

    // ─── 6. Bengaluru Meenakshi Mall (kids) ───────────────────────────
    {
        slug: 'bengaluru-meenakshi-mall',
        type: 'kids',
        city: 'Bengaluru',
        mall: 'Meenakshi Mall',
        stateName: 'Karnataka',
        heroImages: ['/images/locations/bengaluru-meenakshi/hero-1.jpg', '/images/locations/bengaluru-meenakshi/hero-2.jpg', '/images/locations/bengaluru-meenakshi/hero-3.jpg'],
        h1: 'Jump, Slide & Explore at Meenakshi Mall',
        subtitle: 'South Bengaluru\'s favourite indoor kids play destination — vibrant, safe and full of surprises.',
        introHeading: 'Welcome to Jus Jumpin — Meenakshi Mall, Bengaluru',
        introText: 'Conveniently located in Meenakshi Mall on Bannerghatta Road, Jus Jumpin offers families in south Bengaluru a premium indoor play experience that kids absolutely love.',
        flipCardImage: '/images/locations/bengaluru-meenakshi/flip.jpg',
        flipCardBullets: ['Colourful trampoline zone', 'Giant multi-lane slides', 'Interactive obstacle course', 'Dedicated party area'],
        highlights: [
            { title: 'Colour Explosion', emoji: '🎨', paragraph: 'Every zone pops with vibrant colours that excite kids and create an immersive play atmosphere.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Active Bodies', emoji: '💪', paragraph: 'Climbing walls, balance beams and trampolines help kids build strength, coordination and confidence.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Parent Peace', emoji: '☕', paragraph: 'Comfortable seating areas with Wi-Fi and refreshments while your child plays safely nearby.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Party Perfection', emoji: '🎁', paragraph: 'Turn birthdays into lasting memories with our all-inclusive celebration packages.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'Meenakshi Mall, 3rd Floor, Bannerghatta Road, Bengaluru, Karnataka 560076',
        phone: '+91 90000 00006',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.5!2d77.60!3d12.88!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Meenakshi+Mall+Bengaluru',
        reviewUrl: 'https://g.page/r/jusjumpin-bengaluru-meenakshi/review',
        lat: 12.8800,
        lng: 77.6000,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Meenakshi Mall?', answer: 'We are on the 3rd floor of Meenakshi Mall, Bannerghatta Road.' },
            { question: 'Is there a cafe inside?', answer: 'We have a small refreshment counter. The mall\'s food court is also nearby on the same floor.' },
        ]),
        seoTitle: 'Jus Jumpin Bengaluru Meenakshi Mall — Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at Meenakshi Mall, Bengaluru — indoor trampoline park and play area for kids. Slides, ball pools, climbing walls & birthday parties!',
        seoKeywords: 'kids play area meenakshi mall, trampoline park bannerghatta road, jus jumpin bengaluru, indoor playground bengaluru',
        accentColor: '#ffc60b',
    },

    // ─── 7. Dhanbad Prabhatam Mall (adults-kids) ─────────────────────
    {
        slug: 'dhanbad-prabhatam-mall',
        type: 'adults-kids',
        city: 'Dhanbad',
        mall: 'Prabhatam Mall',
        stateName: 'Jharkhand',
        heroImages: ['/images/locations/dhanbad-prabhatam/hero-1.jpg', '/images/locations/dhanbad-prabhatam/hero-2.jpg', '/images/locations/dhanbad-prabhatam/hero-3.jpg'],
        h1: 'Dhanbad\'s Premier Adventure & Trampoline Park',
        subtitle: 'High-energy fun for the whole family — trampolines, ninja courses and more at Prabhatam Mall.',
        introHeading: 'Welcome to Jus Jumpin — Prabhatam Mall, Dhanbad',
        introText: 'Jus Jumpin at Prabhatam Mall brings Dhanbad its first world-class indoor adventure park. Whether you\'re a thrill-seeking teen or a parent looking for safe kids\' play, we\'ve got something for everyone.',
        flipCardImage: '/images/locations/dhanbad-prabhatam/flip.jpg',
        flipCardBullets: ['Trampolines for all ages', 'Ninja warrior course', 'Dedicated kids zone', 'Event & party hosting'],
        highlights: [
            { title: 'First in Dhanbad', emoji: '🏆', paragraph: 'The city\'s first and only indoor trampoline and adventure park — setting a new standard for entertainment.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)' },
            { title: 'All Ages Welcome', emoji: '👨‍👩‍👧', paragraph: 'From toddler soft play to adult ninja courses, every family member finds their perfect zone.', gradient: 'linear-gradient(135deg, #4facfe, #00b9e3)' },
            { title: 'Safety First', emoji: '🛡️', paragraph: 'International-grade equipment, trained supervisors and regular safety audits ensure worry-free play.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Celebrate Big', emoji: '🎉', paragraph: 'Dedicated party rooms, custom decorations and packages for birthdays, school events and corporate outings.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)' },
        ],
        activities: adultsKidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult (1 hr)', weekday: '₹499', weekend: '₹599' },
            { label: 'Adult (2 hr)', weekday: '₹799', weekend: '₹899' },
            { label: 'Combo (Adult+Child)', weekday: '₹849', weekend: '₹999' },
        ],
        ticketNote: 'Grip socks included. Infants under 1 year enter free.',
        address: 'Prabhatam Mall, 2nd Floor, Bank More, Dhanbad, Jharkhand 826001',
        phone: '+91 90000 00007',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3650.2!2d86.45!3d23.79!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Prabhatam+Mall+Dhanbad',
        reviewUrl: 'https://g.page/r/jusjumpin-dhanbad-prabhatam/review',
        lat: 23.7900,
        lng: 86.4500,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Prabhatam Mall?', answer: 'We are on the 2nd floor of Prabhatam Mall, Bank More, Dhanbad.' },
            { question: 'Can adults play on the trampolines?', answer: 'Absolutely! Our adult trampoline zone features heavy-duty beds designed for teens and adults.' },
        ]),
        seoTitle: 'Jus Jumpin Dhanbad Prabhatam Mall — Adventure & Trampoline Park for All Ages',
        seoDescription: 'Visit Jus Jumpin at Prabhatam Mall, Dhanbad — Jharkhand\'s best indoor trampoline park for adults & kids. Ninja course, foam pit & more!',
        seoKeywords: 'trampoline park dhanbad, jus jumpin prabhatam mall, adventure park dhanbad, indoor play area dhanbad',
        accentColor: '#ff3645',
    },

    // ─── 8. Ghatkopar R City Mall (kids) ────────────────────────────
    {
        slug: 'ghatkopar-rcity-mall',
        type: 'kids',
        city: 'Mumbai',
        mall: 'R City Mall',
        stateName: 'Maharashtra',
        heroImages: ['/images/locations/ghatkopar-rcity/hero-1.jpg', '/images/locations/ghatkopar-rcity/hero-2.jpg', '/images/locations/ghatkopar-rcity/hero-3.jpg'],
        h1: 'Mumbai\'s Vibrant Kids Play Zone at R City Mall',
        subtitle: 'Bounce, slide and play in Ghatkopar\'s favourite indoor playground for children.',
        introHeading: 'Welcome to Jus Jumpin — R City Mall, Ghatkopar',
        introText: 'Located inside R City Mall, one of Mumbai\'s largest shopping destinations, Jus Jumpin brings a world of active fun for kids. Safe, colourful and designed to spark joy.',
        flipCardImage: '/images/locations/ghatkopar-rcity/flip.jpg',
        flipCardBullets: ['Trampoline park', 'Ball pool & slides', 'Toddler-safe zone', 'Birthday celebrations'],
        highlights: [
            { title: 'Mall Favourite', emoji: '⭐', paragraph: 'One of R City\'s most visited attractions — families flock here every weekend for guaranteed fun.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Safe Zones', emoji: '🛡️', paragraph: 'Age-separated areas, padded floors and trained supervisors let parents relax with confidence.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Active Kids', emoji: '💃', paragraph: 'Trampolines and obstacle courses keep kids physically active while having the time of their lives.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Party Fun', emoji: '🎈', paragraph: 'Dedicated party area with themed décor and hosts to make birthdays magical.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹549', weekend: '₹649' },
            { label: 'Child (2 hr)', weekday: '₹849', weekend: '₹949' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'R City Mall, 3rd Floor, LBS Marg, Ghatkopar West, Mumbai, Maharashtra 400086',
        phone: '+91 90000 00008',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.0!2d72.91!3d19.08!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+R+City+Mall+Ghatkopar',
        reviewUrl: 'https://g.page/r/jusjumpin-ghatkopar-rcity/review',
        lat: 19.0800,
        lng: 72.9100,
        faqs: makeFaqs([
            { question: 'Which floor is Jus Jumpin on?', answer: 'We are on the 3rd floor of R City Mall, Ghatkopar West.' },
            { question: 'Is there parking at R City?', answer: 'Yes, R City Mall offers multi-level parking with ample space.' },
        ]),
        seoTitle: 'Jus Jumpin Ghatkopar R City Mall — Kids Play Area & Trampoline Park Mumbai',
        seoDescription: 'Jus Jumpin at R City Mall, Ghatkopar — Mumbai\'s best indoor trampoline park & play area for kids. Bounce, slide & celebrate birthdays!',
        seoKeywords: 'kids play area mumbai, trampoline park ghatkopar, r city mall play zone, jus jumpin mumbai',
        accentColor: '#f67edd',
    },

    // ─── 9. Durgapur Junction Mall (adults-kids) ────────────────────
    {
        slug: 'durgapur-junction-mall',
        type: 'adults-kids',
        city: 'Durgapur',
        mall: 'Junction Mall',
        stateName: 'West Bengal',
        heroImages: ['/images/locations/durgapur-junction/hero-1.jpg', '/images/locations/durgapur-junction/hero-2.jpg', '/images/locations/durgapur-junction/hero-3.jpg'],
        h1: 'Durgapur\'s Biggest Adventure & Trampoline Park',
        subtitle: 'Action-packed indoor fun for adults and kids at Junction Mall — trampolines, ninja courses & more.',
        introHeading: 'Welcome to Jus Jumpin — Junction Mall, Durgapur',
        introText: 'Jus Jumpin at Junction Mall is Durgapur\'s ultimate indoor adventure destination. With zones for every age, from toddler soft play to adult ninja courses, the whole family can play together.',
        flipCardImage: '/images/locations/durgapur-junction/flip.jpg',
        flipCardBullets: ['All-ages trampoline park', 'Ninja warrior course', 'Soft play zone', 'Corporate & party events'],
        highlights: [
            { title: 'Durgapur\'s Best', emoji: '🥇', paragraph: 'The city\'s premier indoor adventure park — a landmark entertainment destination at Junction Mall.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)' },
            { title: 'Family Together', emoji: '👨‍👩‍👧‍👦', paragraph: 'Adults and kids play side by side — trampolines, foam pits and dodgeball for everyone.', gradient: 'linear-gradient(135deg, #4facfe, #00b9e3)' },
            { title: 'Top Safety', emoji: '🔒', paragraph: 'International-standard equipment, regular maintenance checks and trained supervisors on every zone.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Events & Parties', emoji: '🎊', paragraph: 'From kids\' birthdays to corporate team outings — we handle events of all sizes with custom packages.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)' },
        ],
        activities: adultsKidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult (1 hr)', weekday: '₹499', weekend: '₹599' },
            { label: 'Adult (2 hr)', weekday: '₹799', weekend: '₹899' },
            { label: 'Combo (Adult+Child)', weekday: '₹849', weekend: '₹999' },
        ],
        ticketNote: 'Grip socks included. Infants under 1 year enter free.',
        address: 'Junction Mall, 2nd Floor, City Centre, Durgapur, West Bengal 713216',
        phone: '+91 90000 00009',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3646.5!2d87.32!3d23.53!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Junction+Mall+Durgapur',
        reviewUrl: 'https://g.page/r/jusjumpin-durgapur-junction/review',
        lat: 23.5300,
        lng: 87.3200,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Junction Mall?', answer: 'We are on the 2nd floor of Junction Mall, City Centre, Durgapur.' },
            { question: 'Do you have activities for adults?', answer: 'Yes! Our ninja course, dodgeball arena and adult trampolines are all designed for teens and adults.' },
        ]),
        seoTitle: 'Jus Jumpin Durgapur Junction Mall — Trampoline & Adventure Park for All Ages',
        seoDescription: 'Jus Jumpin at Junction Mall, Durgapur — indoor trampoline park for adults & kids with ninja courses, foam pits & birthday party packages.',
        seoKeywords: 'trampoline park durgapur, jus jumpin junction mall, adventure park durgapur, indoor play durgapur',
        accentColor: '#ff661a',
    },

    // ─── 10. Nashik City Centre (kids) ──────────────────────────────
    {
        slug: 'nashik-city-centre',
        type: 'kids',
        city: 'Nashik',
        mall: 'City Centre',
        stateName: 'Maharashtra',
        heroImages: ['/images/locations/nashik-cc/hero-1.jpg', '/images/locations/nashik-cc/hero-2.jpg', '/images/locations/nashik-cc/hero-3.jpg'],
        h1: 'Nashik\'s Favourite Kids Play Destination',
        subtitle: 'Colourful, safe and exciting — the ultimate indoor play zone for Nashik\'s young adventurers.',
        introHeading: 'Welcome to Jus Jumpin — City Centre, Nashik',
        introText: 'Jus Jumpin at City Centre brings Nashik an exciting world of indoor play for kids. Our thoughtfully designed zones keep children active, entertained and safe.',
        flipCardImage: '/images/locations/nashik-cc/flip.jpg',
        flipCardBullets: ['Trampoline zone', 'Slides & ball pools', 'Toddler soft play', 'Birthday party packages'],
        highlights: [
            { title: 'Nashik\'s #1', emoji: '🏆', paragraph: 'The most visited kids\' entertainment destination in Nashik — trusted by thousands of families.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Safe Play', emoji: '✅', paragraph: 'Padded zones, CCTV monitoring and trained staff create a worry-free environment for parents.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Creative Fun', emoji: '🎨', paragraph: 'Themed play areas spark imagination and encourage creative, social play among children.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Celebrate', emoji: '🎂', paragraph: 'Host memorable birthday celebrations with custom packages, decorations and a dedicated party host.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'City Centre Mall, 2nd Floor, College Road, Nashik, Maharashtra 422005',
        phone: '+91 90000 00010',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3749.5!2d73.79!3d19.99!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+City+Centre+Nashik',
        reviewUrl: 'https://g.page/r/jusjumpin-nashik-cc/review',
        lat: 19.9900,
        lng: 73.7900,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in City Centre Nashik?', answer: 'We are on the 2nd floor of City Centre Mall, College Road, Nashik.' },
            { question: 'What age group is this for?', answer: 'Our zones cater to children aged 1–14, with a separate soft play area for toddlers under 4.' },
        ]),
        seoTitle: 'Jus Jumpin Nashik City Centre — Best Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at City Centre, Nashik — indoor trampoline park and play area for kids. Trampolines, slides, ball pools & birthday parties!',
        seoKeywords: 'kids play area nashik, trampoline park nashik, jus jumpin nashik, indoor playground nashik',
        accentColor: '#ffc60b',
    },

    // ─── 11. Jamshedpur P&M Mall (kids) ─────────────────────────────
    {
        slug: 'jamshedpur-pm-mall',
        type: 'kids',
        city: 'Jamshedpur',
        mall: 'P&M Mall',
        stateName: 'Jharkhand',
        heroImages: ['/images/locations/jamshedpur-pm/hero-1.jpg', '/images/locations/jamshedpur-pm/hero-2.jpg', '/images/locations/jamshedpur-pm/hero-3.jpg'],
        h1: 'Jump Into Fun at P&M Mall, Jamshedpur',
        subtitle: 'Jamshedpur\'s best indoor kids play park — safe, vibrant and bursting with energy.',
        introHeading: 'Welcome to Jus Jumpin — P&M Mall, Jamshedpur',
        introText: 'Jus Jumpin brings Jamshedpur\'s kids a vibrant indoor playground packed with trampolines, slides and obstacle courses. A perfect outing for the whole family!',
        flipCardImage: '/images/locations/jamshedpur-pm/flip.jpg',
        flipCardBullets: ['Trampolines & ball pools', 'Obstacle course', 'Safe toddler zone', 'Party bookings available'],
        highlights: [
            { title: 'Jump High', emoji: '🚀', paragraph: 'Our interconnected trampoline beds let kids bounce, flip and fly in a safe, padded environment.', gradient: 'linear-gradient(135deg, #4facfe, #00b9e3)' },
            { title: 'Tot Friendly', emoji: '🧸', paragraph: 'Extra-soft foam zones and gentle slides specially designed for children under 5.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
            { title: 'Clean & Safe', emoji: '🧼', paragraph: 'Sanitised after every session with trained supervisors watching over every zone.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Birthday Joy', emoji: '🎁', paragraph: 'All-inclusive birthday packages with private party room, decorations and unlimited play.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'P&M Mall, 2nd Floor, Bistupur, Jamshedpur, Jharkhand 831001',
        phone: '+91 90000 00011',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3672.0!2d86.20!3d22.80!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+PM+Mall+Jamshedpur',
        reviewUrl: 'https://g.page/r/jusjumpin-jamshedpur-pm/review',
        lat: 22.8000,
        lng: 86.2000,
        faqs: makeFaqs([
            { question: 'Where is the play zone in P&M Mall?', answer: 'Jus Jumpin is on the 2nd floor of P&M Mall, Bistupur, Jamshedpur.' },
            { question: 'Is advance booking required?', answer: 'Walk-ins are welcome! Advance booking is only required for birthday parties and group events.' },
        ]),
        seoTitle: 'Jus Jumpin Jamshedpur P&M Mall — Kids Trampoline Park & Play Area',
        seoDescription: 'Jus Jumpin at P&M Mall, Jamshedpur — indoor trampoline park for kids with ball pools, slides, obstacle courses & birthday party venue.',
        seoKeywords: 'kids play area jamshedpur, trampoline park jamshedpur, jus jumpin pm mall, indoor playground jamshedpur',
        accentColor: '#4facfe',
    },

    // ─── 12. Nagpur VR Mall (adults-kids) ───────────────────────────
    {
        slug: 'nagpur-vr-mall',
        type: 'adults-kids',
        city: 'Nagpur',
        mall: 'VR Mall',
        stateName: 'Maharashtra',
        heroImages: ['/images/locations/nagpur-vr/hero-1.jpg', '/images/locations/nagpur-vr/hero-2.jpg', '/images/locations/nagpur-vr/hero-3.jpg'],
        h1: 'Nagpur\'s Biggest Trampoline & Adventure Park',
        subtitle: 'High-energy indoor action for adults and kids at VR Mall — bounce, climb and conquer!',
        introHeading: 'Welcome to Jus Jumpin — VR Mall, Nagpur',
        introText: 'Jus Jumpin at VR Mall is Central India\'s most exciting indoor adventure park. With zones for every age and energy level, it\'s the ultimate family entertainment destination in Nagpur.',
        flipCardImage: '/images/locations/nagpur-vr/flip.jpg',
        flipCardBullets: ['Trampolines for all ages', 'Ninja warrior challenge', 'Kids soft play', 'Group event hosting'],
        highlights: [
            { title: 'Central India\'s Best', emoji: '🌟', paragraph: 'The largest indoor trampoline and adventure park in the region — a must-visit for thrill-seekers.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)' },
            { title: 'Adults Welcome', emoji: '🏋️', paragraph: 'Ninja courses, dodgeball and basketball dunk zones give adults a serious workout disguised as fun.', gradient: 'linear-gradient(135deg, #4facfe, #00b9e3)' },
            { title: 'Kid Zones', emoji: '🧒', paragraph: 'Dedicated soft play, ball pools and scaled-down obstacles keep younger children safe and happy.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Events & Parties', emoji: '🎉', paragraph: 'Birthday packages, school groups and team-building events — we host celebrations of all kinds.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)' },
        ],
        activities: adultsKidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult (1 hr)', weekday: '₹549', weekend: '₹649' },
            { label: 'Adult (2 hr)', weekday: '₹849', weekend: '₹949' },
            { label: 'Combo (Adult+Child)', weekday: '₹899', weekend: '₹1099' },
        ],
        ticketNote: 'Grip socks included. Infants under 1 year enter free.',
        address: 'VR Mall, 3rd Floor, Wardha Road, Nagpur, Maharashtra 440025',
        phone: '+91 90000 00012',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3720.5!2d79.09!3d21.12!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+VR+Mall+Nagpur',
        reviewUrl: 'https://g.page/r/jusjumpin-nagpur-vr/review',
        lat: 21.1200,
        lng: 79.0900,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in VR Mall Nagpur?', answer: 'We are on the 3rd floor of VR Mall, Wardha Road, Nagpur.' },
            { question: 'Is the ninja course safe for beginners?', answer: 'Yes! Our ninja course has multiple difficulty levels, and trained staff help beginners get started safely.' },
        ]),
        seoTitle: 'Jus Jumpin Nagpur VR Mall — Adventure & Trampoline Park for Adults & Kids',
        seoDescription: 'Visit Jus Jumpin at VR Mall, Nagpur — Central India\'s best indoor trampoline park for adults & kids. Ninja courses, foam pits & more!',
        seoKeywords: 'trampoline park nagpur, jus jumpin vr mall, adventure park nagpur, indoor play area nagpur',
        accentColor: '#ff3645',
    },

    // ─── 13. Noida GIP Mall (adults-kids) ───────────────────────────
    {
        slug: 'noida-gip-mall',
        type: 'adults-kids',
        city: 'Noida',
        mall: 'GIP Mall',
        stateName: 'Uttar Pradesh',
        heroImages: ['/images/locations/noida-gip/hero-1.jpg', '/images/locations/noida-gip/hero-2.jpg', '/images/locations/noida-gip/hero-3.jpg'],
        h1: 'Noida\'s Premier Trampoline & Adventure Park',
        subtitle: 'Fly high at GIP Mall — the NCR\'s most thrilling indoor action zone for adults and kids.',
        introHeading: 'Welcome to Jus Jumpin — GIP Mall, Noida',
        introText: 'Inside the iconic Gardens Galleria (GIP) Mall, Jus Jumpin delivers Noida\'s most exhilarating indoor adventure experience. From ninja warrior courses to toddler soft play — fun for every age.',
        flipCardImage: '/images/locations/noida-gip/flip.jpg',
        flipCardBullets: ['NCR\'s largest trampoline zone', 'Full ninja warrior course', 'Dedicated kids area', 'Premium party packages'],
        highlights: [
            { title: 'NCR\'s Finest', emoji: '🏙️', paragraph: 'One of the largest indoor trampoline parks in the National Capital Region — right inside GIP Mall.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)' },
            { title: 'All Ages', emoji: '👨‍👩‍👧‍👦', paragraph: 'Separate zones for toddlers, kids, teens and adults ensure everyone plays at the right intensity.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Pro Safety', emoji: '🛡️', paragraph: 'Olympic-grade padding, harness systems on climbing walls and trained supervisors at every zone.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Premium Events', emoji: '✨', paragraph: 'Corporate team building, birthday bashes and school outings with customised packages.', gradient: 'linear-gradient(135deg, #8869d2, #f67edd)' },
        ],
        activities: adultsKidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹549', weekend: '₹649' },
            { label: 'Child (2 hr)', weekday: '₹849', weekend: '₹949' },
            { label: 'Adult (1 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult (2 hr)', weekday: '₹999', weekend: '₹1099' },
            { label: 'Combo (Adult+Child)', weekday: '₹1099', weekend: '₹1299' },
        ],
        ticketNote: 'Grip socks included. Infants under 1 year enter free.',
        address: 'Gardens Galleria (GIP) Mall, 3rd Floor, Sector 38A, Noida, Uttar Pradesh 201301',
        phone: '+91 90000 00013',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.5!2d77.32!3d28.57!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+GIP+Mall+Noida',
        reviewUrl: 'https://g.page/r/jusjumpin-noida-gip/review',
        lat: 28.5700,
        lng: 77.3200,
        faqs: makeFaqs([
            { question: 'Where exactly in GIP Mall?', answer: 'We are on the 3rd floor of Gardens Galleria (GIP) Mall, Sector 38A, Noida.' },
            { question: 'Is metro access easy?', answer: 'Yes! GIP Mall is a short auto-ride from Botanical Garden Metro Station on the Blue Line.' },
        ]),
        seoTitle: 'Jus Jumpin Noida GIP Mall — Best Trampoline & Adventure Park in NCR',
        seoDescription: 'Jus Jumpin at GIP Mall, Noida — NCR\'s best indoor trampoline park for adults & kids. Ninja courses, foam pits, dodgeball & birthday parties!',
        seoKeywords: 'trampoline park noida, jus jumpin gip mall, adventure park noida, indoor play area ncr',
        accentColor: '#ff661a',
    },

    // ─── 14. Noida Spectrum Mall (kids) ─────────────────────────────
    {
        slug: 'noida-spectrum-mall',
        type: 'kids',
        city: 'Noida',
        mall: 'Spectrum Mall',
        stateName: 'Uttar Pradesh',
        heroImages: ['/images/locations/noida-spectrum/hero-1.jpg', '/images/locations/noida-spectrum/hero-2.jpg', '/images/locations/noida-spectrum/hero-3.jpg'],
        h1: 'Kids\' Fun Paradise at Spectrum Mall, Noida',
        subtitle: 'Noida\'s brightest indoor play zone — trampolines, slides and ball pools for happy kids.',
        introHeading: 'Welcome to Jus Jumpin — Spectrum Mall, Noida',
        introText: 'Located in Spectrum Mall, Sector 75, Jus Jumpin is Noida\'s cheerful destination for kids\' active play. Designed for children aged 1–14 with a focus on safety and fun.',
        flipCardImage: '/images/locations/noida-spectrum/flip.jpg',
        flipCardBullets: ['Trampoline zone', 'Slides & ball pools', 'Soft play for toddlers', 'Weekend birthday parties'],
        highlights: [
            { title: 'Bright & Fun', emoji: '🌈', paragraph: 'Every zone is designed in vibrant colours with engaging themes that kids absolutely love.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
            { title: 'Safe Space', emoji: '🔒', paragraph: 'Age-separated zones, thick padding and always-present supervisors give parents peace of mind.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Active Play', emoji: '⚡', paragraph: 'Trampolines and obstacle courses keep kids physically active while building confidence.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Party Venue', emoji: '🎈', paragraph: 'Private birthday party rooms with themed setups, cake service and a dedicated host.', gradient: 'linear-gradient(135deg, #8869d2, #f67edd)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'Spectrum Mall, 2nd Floor, Sector 75, Noida, Uttar Pradesh 201301',
        phone: '+91 90000 00014',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3505.0!2d77.39!3d28.57!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Spectrum+Mall+Noida',
        reviewUrl: 'https://g.page/r/jusjumpin-noida-spectrum/review',
        lat: 28.5700,
        lng: 77.3900,
        faqs: makeFaqs([
            { question: 'Where in Spectrum Mall?', answer: 'We are on the 2nd floor of Spectrum Mall, Sector 75, Noida.' },
            { question: 'Can my toddler (age 2) play safely?', answer: 'Yes! We have a gated soft play zone with extra-padded surfaces designed exclusively for toddlers aged 1–4.' },
        ]),
        seoTitle: 'Jus Jumpin Noida Spectrum Mall — Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at Spectrum Mall, Noida — indoor trampoline park and play area for kids with ball pools, slides, climbing walls & birthday parties.',
        seoKeywords: 'kids play area noida, trampoline park spectrum mall, jus jumpin noida, indoor playground sector 75',
        accentColor: '#f67edd',
    },

    // ─── 15. Pune Seasons Mall (kids) ───────────────────────────────
    {
        slug: 'pune-seasons-mall',
        type: 'kids',
        city: 'Pune',
        mall: 'Seasons Mall',
        stateName: 'Maharashtra',
        heroImages: ['/images/locations/pune-seasons/hero-1.jpg', '/images/locations/pune-seasons/hero-2.jpg', '/images/locations/pune-seasons/hero-3.jpg'],
        h1: 'Pune\'s Most Fun Kids Play Zone',
        subtitle: 'Colourful trampolines, exciting slides and safe play — all under one roof at Seasons Mall.',
        introHeading: 'Welcome to Jus Jumpin — Seasons Mall, Pune',
        introText: 'Jus Jumpin at Seasons Mall in Magarpatta is Pune\'s premier indoor kids play destination. Bright, clean and designed for maximum fun and safety.',
        flipCardImage: '/images/locations/pune-seasons/flip.jpg',
        flipCardBullets: ['Trampoline zone', 'Ball pool & slides', 'Toddler soft play', 'Birthday party venue'],
        highlights: [
            { title: 'Pune\'s Best', emoji: '🏆', paragraph: 'Consistently rated as Pune\'s top indoor kids play zone by families across the city.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Child Safe', emoji: '🛡️', paragraph: 'Padded surfaces, age-separated zones and CCTV monitoring ensure every child is safe.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Active Fun', emoji: '🤸', paragraph: 'Trampolines, obstacle courses and climbing walls keep kids physically engaged and happy.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Party Time', emoji: '🎂', paragraph: 'Themed birthday party packages with private rooms, decorations and unlimited play.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'Seasons Mall, 2nd Floor, Magarpatta City, Hadapsar, Pune, Maharashtra 411028',
        phone: '+91 90000 00015',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3783.5!2d73.93!3d18.51!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Seasons+Mall+Pune',
        reviewUrl: 'https://g.page/r/jusjumpin-pune-seasons/review',
        lat: 18.5100,
        lng: 73.9300,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Seasons Mall?', answer: 'We are on the 2nd floor of Seasons Mall, Magarpatta City, Hadapsar.' },
            { question: 'Is there a food court nearby?', answer: 'Yes, Seasons Mall has a large food court on the same floor with many options.' },
        ]),
        seoTitle: 'Jus Jumpin Pune Seasons Mall — Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at Seasons Mall, Pune — indoor trampoline park and play area for kids with ball pools, slides & birthday party venue.',
        seoKeywords: 'kids play area pune, trampoline park seasons mall, jus jumpin pune, indoor playground hadapsar',
        accentColor: '#ffc60b',
    },

    // ─── 16. Raipur Zora Mall (adults-kids) ─────────────────────────
    {
        slug: 'raipur-zora-mall',
        type: 'adults-kids',
        city: 'Raipur',
        mall: 'Zora Mall',
        stateName: 'Chhattisgarh',
        heroImages: ['/images/locations/raipur-zora/hero-1.jpg', '/images/locations/raipur-zora/hero-2.jpg', '/images/locations/raipur-zora/hero-3.jpg'],
        h1: 'Raipur\'s Ultimate Trampoline & Adventure Park',
        subtitle: 'High-octane indoor fun for adults and kids at Zora Mall — bounce, climb and conquer!',
        introHeading: 'Welcome to Jus Jumpin — Zora Mall, Raipur',
        introText: 'Jus Jumpin at Zora Mall is Raipur\'s most exciting indoor entertainment venue. With zones for every age, it\'s the perfect destination for family fun, teen adventures and kids\' play.',
        flipCardImage: '/images/locations/raipur-zora/flip.jpg',
        flipCardBullets: ['All-ages trampolines', 'Ninja warrior course', 'Kids soft play', 'Party & event hosting'],
        highlights: [
            { title: 'Raipur\'s First', emoji: '🥇', paragraph: 'Chhattisgarh\'s first world-class indoor trampoline and adventure park — right inside Zora Mall.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)' },
            { title: 'All Ages', emoji: '👨‍👩‍👧‍👦', paragraph: 'From toddler soft play to adult ninja courses, every family member finds their zone.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Safety Assured', emoji: '🔒', paragraph: 'International-grade padding and equipment with trained supervisors on every zone.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Celebrate', emoji: '🎉', paragraph: 'Birthday parties, school groups and corporate events with custom packages.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)' },
        ],
        activities: adultsKidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult (1 hr)', weekday: '₹499', weekend: '₹599' },
            { label: 'Adult (2 hr)', weekday: '₹799', weekend: '₹899' },
            { label: 'Combo (Adult+Child)', weekday: '₹849', weekend: '₹999' },
        ],
        ticketNote: 'Grip socks included. Infants under 1 year enter free.',
        address: 'Zora Mall, 2nd Floor, Fafadih, Raipur, Chhattisgarh 492001',
        phone: '+91 90000 00016',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3718.5!2d81.64!3d21.25!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Zora+Mall+Raipur',
        reviewUrl: 'https://g.page/r/jusjumpin-raipur-zora/review',
        lat: 21.2500,
        lng: 81.6400,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Zora Mall?', answer: 'We are on the 2nd floor of Zora Mall, Fafadih, Raipur.' },
            { question: 'Can adults play too?', answer: 'Absolutely! We have dedicated adult trampoline zones, ninja courses and dodgeball arenas.' },
        ]),
        seoTitle: 'Jus Jumpin Raipur Zora Mall — Trampoline & Adventure Park for All Ages',
        seoDescription: 'Visit Jus Jumpin at Zora Mall, Raipur — Chhattisgarh\'s best indoor trampoline park for adults & kids with ninja courses & party packages.',
        seoKeywords: 'trampoline park raipur, jus jumpin zora mall, adventure park raipur, indoor play area raipur',
        accentColor: '#ff661a',
    },

    // ─── 17. Ranchi Nucleus Mall (kids) ─────────────────────────────
    {
        slug: 'ranchi-nucleus-mall',
        type: 'kids',
        city: 'Ranchi',
        mall: 'Nucleus Mall',
        stateName: 'Jharkhand',
        heroImages: ['/images/locations/ranchi-nucleus/hero-1.jpg', '/images/locations/ranchi-nucleus/hero-2.jpg', '/images/locations/ranchi-nucleus/hero-3.jpg'],
        h1: 'Ranchi\'s Happiest Kids Play Zone',
        subtitle: 'Safe, vibrant and full of fun — Nucleus Mall\'s favourite indoor playground for children.',
        introHeading: 'Welcome to Jus Jumpin — Nucleus Mall, Ranchi',
        introText: 'Jus Jumpin at Nucleus Mall is Ranchi\'s most loved indoor kids play park. Bright, safe and packed with exciting activities for children of all ages.',
        flipCardImage: '/images/locations/ranchi-nucleus/flip.jpg',
        flipCardBullets: ['Trampolines & slides', 'Ball pool paradise', 'Safe toddler zone', 'Birthday party packages'],
        highlights: [
            { title: 'Ranchi\'s #1', emoji: '⭐', paragraph: 'The most popular kids entertainment destination in Ranchi — families love it!', gradient: 'linear-gradient(135deg, #4facfe, #00b9e3)' },
            { title: 'Safe Play', emoji: '✅', paragraph: 'Every zone designed with child safety first — padded, supervised and sanitised.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'All Ages', emoji: '👧', paragraph: 'Activities for toddlers through teens, with separate zones for each age group.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
            { title: 'Parties', emoji: '🎈', paragraph: 'Birthday party packages with dedicated rooms, decorations, food and a party host.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'Nucleus Mall, 3rd Floor, Main Road, Ranchi, Jharkhand 834001',
        phone: '+91 90000 00017',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3662.0!2d85.33!3d23.35!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Nucleus+Mall+Ranchi',
        reviewUrl: 'https://g.page/r/jusjumpin-ranchi-nucleus/review',
        lat: 23.3500,
        lng: 85.3300,
        faqs: makeFaqs([
            { question: 'Which floor is Jus Jumpin on?', answer: 'We are on the 3rd floor of Nucleus Mall, Main Road, Ranchi.' },
            { question: 'Are there activities for teenagers?', answer: 'Yes! Our trampoline zone and obstacle courses are great fun for teens aged 12–16.' },
        ]),
        seoTitle: 'Jus Jumpin Ranchi Nucleus Mall — Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at Nucleus Mall, Ranchi — indoor trampoline park and play area for kids. Trampolines, ball pools, slides & birthday parties!',
        seoKeywords: 'kids play area ranchi, trampoline park ranchi, jus jumpin nucleus mall, indoor playground ranchi',
        accentColor: '#4facfe',
    },

    // ─── 18. Siliguri City Centre (kids) ────────────────────────────
    {
        slug: 'siliguri-city-centre',
        type: 'kids',
        city: 'Siliguri',
        mall: 'City Centre',
        stateName: 'West Bengal',
        heroImages: ['/images/locations/siliguri-cc/hero-1.jpg', '/images/locations/siliguri-cc/hero-2.jpg', '/images/locations/siliguri-cc/hero-3.jpg'],
        h1: 'Siliguri\'s Best Kids Indoor Play Park',
        subtitle: 'North Bengal\'s favourite destination for kids\' active fun — trampolines, slides and more.',
        introHeading: 'Welcome to Jus Jumpin — City Centre, Siliguri',
        introText: 'Jus Jumpin at City Centre Siliguri brings North Bengal a world-class indoor play experience. Safe, vibrant and packed with activities that kids absolutely love.',
        flipCardImage: '/images/locations/siliguri-cc/flip.jpg',
        flipCardBullets: ['Trampoline zone', 'Slides & ball pools', 'Dedicated toddler area', 'Party bookings'],
        highlights: [
            { title: 'North Bengal\'s Best', emoji: '🏔️', paragraph: 'The region\'s premier indoor kids play park — a must-visit for families in Siliguri.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Safe & Fun', emoji: '🛡️', paragraph: 'Padded zones, trained supervisors and regular sanitisation for worry-free play.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Active Kids', emoji: '🏃', paragraph: 'Trampolines and obstacle courses develop fitness, balance and coordination.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Celebrate', emoji: '🎊', paragraph: 'Host birthday parties with themed setups and unlimited play for all guests.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'City Centre Mall, 2nd Floor, Sevoke Road, Siliguri, West Bengal 734001',
        phone: '+91 90000 00018',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3565.5!2d88.43!3d26.72!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+City+Centre+Siliguri',
        reviewUrl: 'https://g.page/r/jusjumpin-siliguri-cc/review',
        lat: 26.7200,
        lng: 88.4300,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in City Centre Siliguri?', answer: 'We are on the 2nd floor of City Centre Mall, Sevoke Road, Siliguri.' },
            { question: 'Is it good for a rainy day?', answer: 'It\'s the perfect rainy-day activity! Our indoor facility means fun regardless of weather.' },
        ]),
        seoTitle: 'Jus Jumpin Siliguri City Centre — Kids Trampoline Park & Play Area',
        seoDescription: 'Jus Jumpin at City Centre, Siliguri — North Bengal\'s best indoor trampoline park for kids with slides, ball pools & birthday parties.',
        seoKeywords: 'kids play area siliguri, trampoline park siliguri, jus jumpin city centre siliguri, indoor playground siliguri',
        accentColor: '#00b9e3',
    },

    // ─── 19. Surat VR Mall (kids) ───────────────────────────────────
    {
        slug: 'surat-vr-mall',
        type: 'kids',
        city: 'Surat',
        mall: 'VR Mall',
        stateName: 'Gujarat',
        heroImages: ['/images/locations/surat-vr/hero-1.jpg', '/images/locations/surat-vr/hero-2.jpg', '/images/locations/surat-vr/hero-3.jpg'],
        h1: 'Surat\'s Most Exciting Kids Play Zone',
        subtitle: 'Gujarat\'s favourite indoor play park — trampolines, ball pools and endless fun at VR Mall.',
        introHeading: 'Welcome to Jus Jumpin — VR Mall, Surat',
        introText: 'Jus Jumpin at VR Mall in Surat is Gujarat\'s go-to destination for kids\' indoor entertainment. Colourful, safe and designed to delight children of every age.',
        flipCardImage: '/images/locations/surat-vr/flip.jpg',
        flipCardBullets: ['Trampoline park', 'Ball pool & slides', 'Soft play for tots', 'Birthday party packages'],
        highlights: [
            { title: 'Gujarat\'s Best', emoji: '🌟', paragraph: 'The most popular kids play zone in Gujarat — vibrant, safe and loved by families.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
            { title: 'Safe & Clean', emoji: '✨', paragraph: 'Regular sanitisation, padded zones and trained staff for a worry-free experience.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Fun Activities', emoji: '🎯', paragraph: 'From trampolines to obstacle courses, every zone is designed for active, joyful play.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Party Zone', emoji: '🎂', paragraph: 'Celebrate birthdays with custom packages, dedicated host and unlimited play.', gradient: 'linear-gradient(135deg, #f67edd, #ff5da0)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹449', weekend: '₹549' },
            { label: 'Child (2 hr)', weekday: '₹699', weekend: '₹799' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'VR Mall, 3rd Floor, Dumas Road, Surat, Gujarat 395007',
        phone: '+91 90000 00019',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3719.0!2d72.82!3d21.17!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+VR+Mall+Surat',
        reviewUrl: 'https://g.page/r/jusjumpin-surat-vr/review',
        lat: 21.1700,
        lng: 72.8200,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in VR Mall Surat?', answer: 'We are on the 3rd floor of VR Mall, Dumas Road, Surat.' },
            { question: 'Do you offer group discounts?', answer: 'Yes! We have special rates for groups of 10 or more. Contact us for details.' },
        ]),
        seoTitle: 'Jus Jumpin Surat VR Mall — Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at VR Mall, Surat — Gujarat\'s best indoor trampoline park and play area for kids. Ball pools, slides & birthday parties!',
        seoKeywords: 'kids play area surat, trampoline park surat, jus jumpin vr mall surat, indoor playground surat',
        accentColor: '#ffc60b',
    },

    // ─── 20. Udaipur Urban Square Mall (kids) ───────────────────────
    {
        slug: 'udaipur-urban-square-mall',
        type: 'kids',
        city: 'Udaipur',
        mall: 'Urban Square Mall',
        stateName: 'Rajasthan',
        heroImages: ['/images/locations/udaipur-urban/hero-1.jpg', '/images/locations/udaipur-urban/hero-2.jpg', '/images/locations/udaipur-urban/hero-3.jpg'],
        h1: 'Udaipur\'s Favourite Kids Play Park',
        subtitle: 'Rajasthan\'s most vibrant indoor kids play zone — trampolines, slides and pure joy.',
        introHeading: 'Welcome to Jus Jumpin — Urban Square Mall, Udaipur',
        introText: 'Jus Jumpin at Urban Square Mall brings Udaipur families a premium indoor play experience. Bright, safe and designed for kids aged 1–14 to have the time of their lives.',
        flipCardImage: '/images/locations/udaipur-urban/flip.jpg',
        flipCardBullets: ['Trampoline zone', 'Slides & ball pool', 'Toddler soft play', 'Birthday celebrations'],
        highlights: [
            { title: 'Udaipur\'s Pride', emoji: '🏰', paragraph: 'The city\'s most popular kids entertainment venue — a proud addition to Urban Square Mall.', gradient: 'linear-gradient(135deg, #8869d2, #f67edd)' },
            { title: 'Safe Fun', emoji: '🛡️', paragraph: 'Padded zones, trained staff and hygiene protocols ensure a worry-free visit for families.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Active Play', emoji: '💪', paragraph: 'Our zones develop coordination, balance and physical fitness while keeping kids delighted.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Dream Parties', emoji: '✨', paragraph: 'Themed birthday party packages with private rooms, cakes and unlimited play.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹399', weekend: '₹499' },
            { label: 'Child (2 hr)', weekday: '₹649', weekend: '₹749' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'Urban Square Mall, 2nd Floor, Udaipur, Rajasthan 313001',
        phone: '+91 90000 00020',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3631.5!2d73.69!3d24.58!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+Urban+Square+Mall+Udaipur',
        reviewUrl: 'https://g.page/r/jusjumpin-udaipur-urban/review',
        lat: 24.5800,
        lng: 73.6900,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in Urban Square Mall?', answer: 'We are on the 2nd floor of Urban Square Mall, Udaipur.' },
            { question: 'Is there parking available?', answer: 'Yes, Urban Square Mall offers multi-level parking with ample space for visitors.' },
        ]),
        seoTitle: 'Jus Jumpin Udaipur Urban Square Mall — Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at Urban Square Mall, Udaipur — Rajasthan\'s best indoor kids play area with trampolines, slides, ball pools & birthday parties.',
        seoKeywords: 'kids play area udaipur, trampoline park udaipur, jus jumpin urban square, indoor playground udaipur',
        accentColor: '#8869d2',
    },

    // ─── 21. Thane R Mall (kids) ────────────────────────────────────
    {
        slug: 'thane-r-mall',
        type: 'kids',
        city: 'Thane',
        mall: 'R Mall',
        stateName: 'Maharashtra',
        heroImages: ['/images/locations/thane-rmall/hero-1.jpg', '/images/locations/thane-rmall/hero-2.jpg', '/images/locations/thane-rmall/hero-3.jpg'],
        h1: 'Thane\'s Most Loved Kids Play Zone',
        subtitle: 'Vibrant, safe and fun-filled — the ultimate indoor playground for Thane\'s young explorers.',
        introHeading: 'Welcome to Jus Jumpin — R Mall, Thane',
        introText: 'Located in R Mall on Ghodbunder Road, Jus Jumpin is Thane\'s most popular indoor play destination. Packed with trampolines, slides and safe play zones for kids of all ages.',
        flipCardImage: '/images/locations/thane-rmall/flip.jpg',
        flipCardBullets: ['Trampoline park', 'Slides & ball pools', 'Toddler-safe zone', 'Birthday party venue'],
        highlights: [
            { title: 'Thane\'s Favourite', emoji: '❤️', paragraph: 'The most visited kids play zone in Thane — families trust us for safe, exciting entertainment.', gradient: 'linear-gradient(135deg, #ff5da0, #f67edd)' },
            { title: 'Safe Zones', emoji: '🛡️', paragraph: 'Age-separated areas with padded surfaces, trained supervisors and regular sanitisation.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)' },
            { title: 'Active Fun', emoji: '🤸', paragraph: 'Trampolines, obstacle courses and climbing walls keep kids moving, laughing and growing.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)' },
            { title: 'Party Time', emoji: '🎁', paragraph: 'Themed birthday packages with private party rooms, food and unlimited play for guests.', gradient: 'linear-gradient(135deg, #ffc60b, #ff661a)' },
        ],
        activities: kidsActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: 'Child (1 hr)', weekday: '₹499', weekend: '₹599' },
            { label: 'Child (2 hr)', weekday: '₹799', weekend: '₹899' },
            { label: 'Adult Companion', weekday: 'Free', weekend: 'Free' },
        ],
        ticketNote: 'Grip socks included. One accompanying adult enters free per child.',
        address: 'R Mall, 2nd Floor, Ghodbunder Road, Thane West, Maharashtra 400607',
        phone: '+91 90000 00021',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3768.5!2d72.96!3d19.22!2m3!1f0!2f0!3f0',
        mapsDirectionsUrl: 'https://maps.google.com/?q=Jus+Jumpin+R+Mall+Thane',
        reviewUrl: 'https://g.page/r/jusjumpin-thane-rmall/review',
        lat: 19.2200,
        lng: 72.9600,
        faqs: makeFaqs([
            { question: 'Where is Jus Jumpin in R Mall?', answer: 'We are on the 2nd floor of R Mall, Ghodbunder Road, Thane West.' },
            { question: 'Is there a separate area for very young kids?', answer: 'Yes, we have a dedicated soft play zone for toddlers aged 1–4 with extra cushioning.' },
        ]),
        seoTitle: 'Jus Jumpin Thane R Mall — Kids Play Area & Trampoline Park',
        seoDescription: 'Jus Jumpin at R Mall, Thane — indoor trampoline park and play area for kids with ball pools, slides, climbing walls & birthday party venue.',
        seoKeywords: 'kids play area thane, trampoline park thane, jus jumpin r mall thane, indoor playground ghodbunder road',
        accentColor: '#ff5da0',
    },
    {
        slug: 'hyderabad-sarath-city-capital-mall',
        type: 'adults-kids',
        city: 'Hyderabad',
        mall: 'Sarath City Capital Mall',
        stateName: 'Telangana',
        heroImages: [
            'https://www.jusjumpin.com/wp-content/uploads/2026/07/Sarath-city-Mall-Hyderabad.png',
            'https://www.jusjumpin.com/wp-content/uploads/2026/07/Sarath-city-capital-Mall.png',
            'https://www.jusjumpin.com/wp-content/uploads/2026/07/activity2.png'
        ],
        h1: 'Jus Jumpin Sarath City Capital Mall',
        subtitle: 'Dive into the world of pure joy and laughter at Jus Jumpin. With more than 20 exciting gaming activities for every fun loving soul.',
        introHeading: 'Ultimate Fun Awaits',
        introText: 'Jump into a whole new world of laughter and joy at Jus Jumpin, Sarath City Capital Mall, the ultimate indoor playzone in Hyderabad. Laced with 20+ exciting activities and attractions, Jus Jumpin creates a perfect world full of fun, where your age means absolutely nothing. Designed to cater to the fun-loving kid inside you, Jus Jumpin at Sarath City Capital Mall offers an infinity trampoline, a knee-shaking adventure course, a wall climb, a zip line, and a bunch of activities you can’t resist. Built to host every age of fun-loving people, Jus Jumpin Sarath City Capital Mall consists of dedicated play zones for kids and adults. At our facilities, we adhere to global safety standards and an impeccably hygienic environment, so you can worry less and jump more. Besides a world-class infinity trampoline and indoor play area in Hyderabad, Jus Jumpin also comes with an awesome party zone to host vibrant birthday parties for Kids. Along with custom decoration, affordable birthday party packages, and food tailored to your preference, we provide magic shows, tattoo artists, and numerous party activities to turn your party into a day to remember.',
        flipCardImage: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/sarath-City.png',
        flipCardBullets: [
            'Infinity trampoline & play area',
            'Dedicated play zones for kids & adults',
            '20+ exciting activities & attractions',
            'Awesome birthday party zone'
        ],
        highlights: [
            { title: 'Amazing Kitty Parties', emoji: '🎂', paragraph: 'Dedicated party area perfect for hosting amazing birthday parties, kitty parties, and corporate events in Hyderabad.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/sarath-City.png' },
            { title: 'Corporate Events', emoji: '🏢', paragraph: 'Vibrant theme decorations, flexible birthday packages, and customizable corporate event setups.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/sarath-City.png' },
            { title: 'Family Celebrations', emoji: '👨\u200D👩\u200D👧\u200D👦', paragraph: 'A world-class infinity trampoline and play park built to host fun-loving people of all ages.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/sarath-City.png' },
            { title: 'Inhouse Cafe (Jus\' Bites)', emoji: '🍹', paragraph: 'Vibrant decor, cool music, and an inhouse cafe serving delicious food tailored to your preference.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/sarath-City.png' }
        ],
        activities: hyderabadActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: '90 Minutes', weekday: '₹650', weekend: '₹750' },
            { label: '120 Minutes', weekday: '₹850', weekend: '₹950' },
        ],
        ticketNote: 'Anti-Skid Grip Socks (One-time purchase, compulsory): ₹50 | Extensions: ₹250/₹450',
        address: 'JUS JUMPIN, Unit No. SF - 26-30, 4th Floor, Sarath City Capital Mall, Gachibowli Rd, Kondapur, Whitefields, HITEC City, Hyderabad, Telangana 500084',
        phone: '+91 9836888333',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31644.387475892054!2d78.33894525257719!3d17.453833537431986!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb93ba1cc0bc19%3A0x80a949c1d6777179!2sJus&#39;%20Jumpin&#39;%20%7C%7C%20Trampoline%20%26%20Adventure%20Park!5e0!3m2!1sen!2sin!4v1783949963617!5m2!1sen!2sin',
        mapsDirectionsUrl: 'https://maps.app.goo.gl/WFXLjjgzWDAPsJr67',
        reviewUrl: 'https://reviewthis.biz/jusjumpin-sarathcity',
        lat: 17.4538,
        lng: 78.3389,
        faqs: makeFaqs([
            { question: 'Is there any age limit at Jus Jumpin\' Trampoline Park?', answer: 'At Jus Jumpin, we believe that age shouldn\'t limit you from having fun. All the age groups can visit our adult trampoline parks and enjoy to the fullest.' },
            { question: 'What are the activities Jus Jumpin offers?', answer: 'At our selected venues, Jus Jumpin offers versatile play activities for both kids and adults. At our facilities, you can find dedicated zones for different age groups.' },
            { question: 'Are there packages, parties, or group rates for adults?', answer: 'Our vibrant theme parks are absolutely epic for hosting birthday parties and social events. For group or bulk bookings, contact our dedicated sales team for irresistible offers.' },
            { question: 'Are there any health / age / weight restrictions?', answer: 'Although at Jus Jumpin, everyone can enjoy without any restrictions, we cordially suggest pregnant guests and guests with heart conditions not participate for safety reasons. The standard weight limit at our facility is up to 100kg, but it totally depends on specific activities.' },
            { question: 'Do I need to sign a waiver?', answer: 'Yes, it is mandatory to ensure you are aware of our facility\'s safety guidelines. For minors, the waiver form must be signed by the guardian.' },
            { question: 'What to wear while visiting Jus Jumpin?', answer: 'While there is no such dress code at Jus Jumpin, we recommend wearing comfortable clothes and mandatory grip socks to ensure the safety of the guests.' }
        ]),
        seoTitle: 'Sarath city capital mall | Jus Jumpin',
        seoDescription: 'Jus Jumpin is an indoor trampoline park and kids entertainment zone — perfect for playful kids and thrill-loving adults looking to unleash their inner jumper.',
        seoKeywords: 'trampoline park, kids entertainment zone, indoor play area, jump fun, Hyderabad, Sarath City Mall',
        accentColor: '#00d9a6',
    },
    {
        slug: 'hyderabad-dsl-virtue-mall',
        type: 'kids',
        city: 'Hyderabad',
        mall: 'DSL Virtue Mall',
        stateName: 'Telangana',
        heroImages: [
            'https://www.jusjumpin.com/wp-content/uploads/2026/07/dsl-virtue-mall-uppal-hyderabad-malls-f8t2ftz7d5.jpg',
            'https://www.jusjumpin.com/wp-content/uploads/2026/07/DJI_0668-scaled-1.jpg',
            'https://www.jusjumpin.com/wp-content/uploads/2026/07/dsl-virtue-mall-cover-image.png'
        ],
        h1: 'Jus Jumpin DSL Virtue Mall, Hyderabad',
        subtitle: 'Dive into the world of pure joy and laughter at Jus Jumpin. With more than 15 thrilling gaming activities for kids, soft playzone, and a large range of delicious food, a memorable day out is guaranteed.',
        introHeading: 'Ultimate Fun Awaits',
        introText: 'Jump into a brand new world full of laughter and fun, at Jus Jumpin, DSL Virtue Mall. Our uplifting kids\' play zone and adventure park is thoughtfully designed to provide a vibrant and safe space for kids aged between 6 months to 12 years, to play without restrictions. With special attractions like vibrant trampoline park, exciting slides, hanging bridge, toddler play zone, and wall climbers, Jus Jumpin hails as the best kids playzone in Hyderabad. Jus Jumpin also acts as the finest venue for birthday party of your child. You can get customized cartoon or anime-themed decorations, an extensive menu curated to your needs, and access to our indoor sports layout, where your kids can play all day long. For the caring parents, we have a cozy lounge area where they can relax comfortably, while their children can explore the new limits of their imagination and play with no restrictions. With more than 15+ games and joyrides, Jus Jumpin creates laughter, energy among kids and wholesome memories for the parents. Jus Jumpin at DSL Virtue Mall is dedicated to providing a safe and fun-filled experience to the tiny jumpers with thrilling wall-to-wall trampolines for kids, exciting wave slides, spiral slides, adventure obstacle games for children, and an interactive soft play zone. With certified safety and hygiene standards, caring parents can entrust their little one with Jus Jumpin and have peace of mind.',
        flipCardImage: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/cover-image.png',
        flipCardBullets: [
            'Trampolines, slides & toddler zones',
            '15+ exciting games & joyrides',
            'Finest children\'s birthday venue',
            'Cozy lounge area for parents'
        ],
        highlights: [
            { title: 'Creative Activities', emoji: '📚', paragraph: 'Experience creative & educational activities designed to stimulate curiosity and motor development.', gradient: 'linear-gradient(135deg, #ff661a, #ff3645)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/cover-image.png' },
            { title: 'Age Specific Zones', emoji: '👶', paragraph: 'Padded spaces tailored to different age groups from infants to kids up to 12 years.', gradient: 'linear-gradient(135deg, #00b9e3, #4facfe)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/cover-image.png' },
            { title: 'Perfect Birthdays', emoji: '🎂', paragraph: 'Private party areas with cartoon/anime themes, customized decorations, and custom menus.', gradient: 'linear-gradient(135deg, #6dc065, #b2d235)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/cover-image.png' },
            { title: 'Resting Zone', emoji: '🛋️', paragraph: 'A cozy lounge area where parents can relax comfortably while their children explore.', gradient: 'linear-gradient(135deg, #f67edd, #8869d2)', image: 'https://www.jusjumpin.com/wp-content/uploads/2026/07/cover-image.png' }
        ],
        activities: dslVirtueActivities,
        weekdayHours: WEEKDAY_HOURS,
        weekendHours: WEEKEND_HOURS,
        pricing: [
            { label: '60 Minutes', weekday: '₹550', weekend: '₹550' },
            { label: '90 Minutes', weekday: '₹650', weekend: '₹650' },
        ],
        ticketNote: 'Anti-Skid Grip Socks compulsory (compulsory for safety & hygiene): ₹50 | Extensions: ₹200 / ₹400',
        address: '2nd Floor, DSL Virtue Mall, Unit No. SF 27, 28, 29, near Rajiv Gandhi International Cricket Stadium, Industrial Development Area, Uppal, Hyderabad, Telangana 500039',
        phone: '+91 9830359999',
        mapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d237.95368802562894!2d78.55516850259671!3d17.399353436986623!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb99d9d44113a3%3A0xd66edde834fb7528!2sJus&#39;%20Jumpin&#39;%20%7C%7C%20Kid&#39;s%20Activity%20and%20Soft%20Play%20Zone!5e0!3m2!1sen!2sin!4v1785138544653!5m2!1sen!2sin',
        mapsDirectionsUrl: 'https://www.google.com/maps/search/?api=1&query=DSL+Virtue+Mall+Uppal+Hyderabad',
        reviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJoxNB1NmZyzsRKHX7NOjdbtY',
        lat: 17.40018,
        lng: 78.55506,
        faqs: makeFaqs([
            { question: 'What age group of Kids can play at Jus Jumpin?', answer: 'All the children aged between 6 months to 12 years can jump into our kids\' playzone.' },
            { question: 'Can adults also play in the play area?', answer: 'For the not-so-little jumpers, Jus Jumpin have specific venues where the adults can have a fun time.' },
            { question: 'What activities are available at Jus Jumpin?', answer: 'At our indoor play zones for kids, we offer a large range of action-packed activities, including trampoline park, toddler play zones, colourful sides, obstacle courses and more than 15 gaming activities.' },
            { question: 'Does Jus Jumpin offer any special packages or Party offers?', answer: 'Our dedicated party zone is one of the best spots to host a birthday party for your little one. We brighten up parties and gatherings with personalised decorations, tattoo artists, mascots and gaming activities. For special offers and packages, you can contact our dedicated sales team.' },
            { question: 'Can I host a birthday party at Jus Jumpin?', answer: 'Our vibrant indoor party area provides a safe and fun-packed environment, along with dedicated party zones to host the best birthday parties for kids.' },
            { question: 'Is outside food allowed in the play area?', answer: 'To maintain safety and hygiene standards at our facilities, we don\'t allow outside food. The guests can savour our in-house snacks and refreshments.' }
        ]),
        seoTitle: 'Hyderabad - DSL Virtue Mall',
        seoDescription: 'Visit Kids Playzone at DSL Virtue Mall Hyderabad—top indoor play area & adventure park, perfect for fun-filled kids’ birthday party celebrations.',
        seoKeywords: 'trampoline park, kids entertainment zone, indoor play area, jump fun, Hyderabad, DSL Virtue Mall',
        accentColor: '#00b9e3',
    },
];

// ── Lookup helper ───────────────────────────────────────────────────
export function getLocation(slug: string): LocationData | undefined {
    return locations.find((l) => l.slug === slug);
}

// ── All slugs (for generateStaticParams) ────────────────────────────
export function getAllSlugs(): string[] {
    return locations.map((l) => l.slug);
}
